name: Dev Container

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  devcontainer:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          subFolder: src-devc
          imageName: opencodeco/phpctl:php83-devcontainer
          push: always
