name: Docker Image CI
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
        - php82
        - php83
          
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --build-arg PHP=${{ matrix.php }} -t opencodeco/phpctl:php${{ matrix.php }} .
