name: Docker

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 81
          - 82
          - 83
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          build-args: PHP=${{ matrix.php }}
          tags: opencodeco/phpctl:php${{ matrix.php }}
      -
        name: Test
        env:
          PHP_VERSION: ${{ matrix.php }}
          PHPCTL_TTY: --label=no-tty
        run: |
          ./lib/bashunit ./tests/
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: PHP=${{ matrix.php }}
          tags: opencodeco/phpctl:php${{ matrix.php }}
