name: Docker
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
        - 82
        - 83
          
    steps:
    - uses: actions/checkout@v3
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        build-args: PHP=${{ matrix.php }}
        tags: opencodeco/phpctl:php${{ matrix.php }}
  
